version: '3.1'

services:
  backend:
    container_name: gb_hh_backend
    build:
      context: ./hh
      dockerfile: Dockerfile
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/templates
      - media_volume:/home/app/backend/media
    expose:
      - 8000
    env_file:
      - ./.env
    links:
      - redis
    depends_on:
      - db

  db:
    container_name: gb_hh_db
    image: postgres:13.0-alpine
    privileged: true
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=jobhunter
    env_file:
      - ./.env

  redis:
    container_name: gb_hh_redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    container_name: gb_hh_nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/backend/templates
      - media_volume:/home/app/backend/media
    ports:
      - "9080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
